const SP500_COMPONENTS = [
  ["NVDA", "NVIDIA Corporation"],
  ["AAPL", "Apple Inc."],
  ["GOOGL", "Alphabet Inc. (Class A)"],
  ["GOOG", "Alphabet Inc. (Class C)"],
  ["MSFT", "Microsoft Corporation"],
  ["AMZN", "Amazon.com, Inc."],
  ["META", "Meta Platforms, Inc."],
  ["AVGO", "Broadcom Inc."],
  ["TSLA", "Tesla, Inc."],
  ["BRK.B", "Berkshire Hathaway Inc."],
  ["WMT", "Walmart Inc."],
  ["LLY", "Eli Lilly and Company"],
  ["JPM", "JPMorgan Chase & Co."],
  ["XOM", "Exxon Mobil Corporation"],
  ["V", "Visa Inc."],
  ["JNJ", "Johnson & Johnson"],
  ["MU", "Micron Technology, Inc."],
  ["COST", "Costco Wholesale Corporation"],
  ["ORCL", "Oracle Corporation"],
  ["MA", "Mastercard Incorporated"],
  ["NFLX", "Netflix, Inc."],
  ["CVX", "Chevron Corporation"],
  ["ABBV", "AbbVie Inc."],
  ["PLTR", "Palantir Technologies Inc."],
  ["PG", "The Procter & Gamble Company"],
  ["HD", "The Home Depot, Inc."],
  ["BAC", "Bank of America Corporation"],
  ["KO", "The Coca-Cola Company"],
  ["CAT", "Caterpillar Inc."],
  ["AMD", "Advanced Micro Devices, Inc."],
  ["GE", "GE Aerospace"],
  ["CSCO", "Cisco Systems, Inc."],
  ["MRK", "Merck & Co., Inc."],
  ["RTX", "RTX Corporation"],
  ["PM", "Philip Morris International Inc."],
  ["AMAT", "Applied Materials, Inc."],
  ["LRCX", "Lam Research Corporation"],
  ["UNH", "UnitedHealth Group Incorporated"],
  ["MS", "Morgan Stanley"],
  ["TMUS", "T-Mobile US, Inc."],
  ["GS", "The Goldman Sachs Group, Inc."],
  ["MCD", "McDonald's Corporation"],
  ["IBM", "International Business Machines Corporation"],
  ["LIN", "Linde plc"],
  ["WFC", "Wells Fargo & Company"],
  ["INTC", "Intel Corporation"],
  ["PEP", "PepsiCo, Inc."],
  ["GEV", "GE Vernova Inc."],
  ["VZ", "Verizon Communications Inc."],
  ["AXP", "American Express Company"],
  ["AMGN", "Amgen Inc."],
  ["T", "AT&T Inc."],
  ["NEE", "NextEra Energy, Inc."],
  ["ABT", "Abbott Laboratories"],
  ["KLAC", "KLA Corporation"],
  ["C", "Citigroup Inc."],
  ["GILD", "Gilead Sciences, Inc."],
  ["CRM", "Salesforce, Inc."],
  ["DIS", "The Walt Disney Company"],
  ["TXN", "Texas Instruments Incorporated"],
  ["TJX", "The TJX Companies, Inc."],
  ["TMO", "Thermo Fisher Scientific Inc."],
  ["ANET", "Arista Networks, Inc."],
  ["ISRG", "Intuitive Surgical, Inc."],
  ["BA", "The Boeing Company"],
  ["APH", "Amphenol Corporation"],
  ["SCHW", "The Charles Schwab Corporation"],
  ["DE", "Deere & Company"],
  ["APP", "AppLovin Corporation"],
  ["PFE", "Pfizer Inc."],
  ["UBER", "Uber Technologies, Inc."],
  ["ADI", "Analog Devices, Inc."],
  ["HON", "Honeywell International Inc."],
  ["COP", "ConocoPhillips"],
  ["LMT", "Lockheed Martin Corporation"],
  ["WELL", "Welltower Inc."],
  ["UNP", "Union Pacific Corporation"],
  ["BLK", "BlackRock, Inc."],
  ["QCOM", "QUALCOMM Incorporated"],
  ["ETN", "Eaton Corporation plc"],
  ["PANW", "Palo Alto Networks, Inc."],
  ["BKNG", "Booking Holdings Inc."],
  ["LOW", "Lowe's Companies, Inc."],
  ["DHR", "Danaher Corporation"],
  ["SYK", "Stryker Corporation"],
  ["CB", "Chubb Limited"],
  ["SPGI", "S&P Global Inc."],
  ["PLD", "Prologis, Inc."],
  ["INTU", "Intuit Inc."],
  ["ACN", "Accenture plc"],
  ["BMY", "Bristol-Myers Squibb Company"],
  ["PGR", "The Progressive Corporation"],
  ["VRTX", "Vertex Pharmaceuticals Incorporated"],
  ["NEM", "Newmont Corporation"],
  ["HCA", "HCA Healthcare, Inc."],
  ["NOW", "ServiceNow, Inc."],
  ["MCK", "McKesson Corporation"],
  ["MO", "Altria Group, Inc."],
  ["SBUX", "Starbucks Corporation"],
  ["PH", "Parker-Hannifin Corporation"],
  ["CRWD", "CrowdStrike Holdings, Inc."],
  ["MDT", "Medtronic plc"],
  ["COF", "Capital One Financial Corporation"],
  ["CME", "CME Group Inc."],
  ["GLW", "Corning Incorporated"],
  ["SO", "The Southern Company"],
  ["CEG", "Constellation Energy Corporation"],
  ["CMCSA", "Comcast Corporation"],
  ["NOC", "Northrop Grumman Corporation"],
  ["DUK", "Duke Energy Corporation"],
  ["BSX", "Boston Scientific Corporation"],
  ["ADBE", "Adobe Inc."],
  ["DELL", "Dell Technologies Inc."],
  ["SNDK", "Sandisk Corporation"],
  ["CVS", "CVS Health Corporation"],
  ["WM", "Waste Management, Inc."],
  ["NRG", "NRG Energy, Inc."],
  ["EQIX", "Equinix, Inc."],
  ["GD", "General Dynamics Corporation"],
  ["HWM", "Howmet Aerospace Inc."],
  ["TT", "Trane Technologies plc"],
  ["WDC", "Western Digital Corporation"],
  ["ICE", "Intercontinental Exchange, Inc."],
  ["WMB", "The Williams Companies, Inc."],
  ["AMT", "American Tower Corporation"],
  ["ADP", "Automatic Data Processing, Inc."],
  ["STX", "Seagate Technology Holdings plc"],
  ["PWR", "Quanta Services, Inc."],
  ["MRSH", "Marsh & McLennan Companies, Inc."],
  ["MAR", "Marriott International, Inc."],
  ["FDX", "FedEx Corporation"],
  ["UPS", "United Parcel Service, Inc."],
  ["PNC", "The PNC Financial Services Group, Inc."],
  ["FCX", "Freeport-McMoRan Inc."],
  ["NKE", "NIKE, Inc."],
  ["BK", "The Bank of New York Mellon Corporation"],
  ["JCI", "Johnson Controls International plc"],
  ["MMM", "3M Company"],
  ["BX", "Blackstone Inc."],
  ["SHW", "The Sherwin-Williams Company"],
  ["USB", "U.S. Bancorp"],
  ["SNPS", "Synopsys, Inc."],
  ["REGN", "Regeneron Pharmaceuticals, Inc."],
  ["MSI", "Motorola Solutions, Inc."],
  ["CDNS", "Cadence Design Systems, Inc."],
  ["CTAS", "Cintas Corporation"],
  ["ECL", "Ecolab Inc."],
  ["ITW", "Illinois Tool Works Inc."],
  ["ABNB", "Airbnb, Inc."],
  ["ORLY", "O'Reilly Automotive, Inc."],
  ["KKR", "KKR & Co. Inc."],
  ["MCO", "Moody's Corporation"],
  ["MNST", "Monster Beverage Corporation"],
  ["EMR", "Emerson Electric Co."],
  ["KMI", "Kinder Morgan, Inc."],
  ["CMI", "Cummins Inc."],
  ["RCL", "Royal Caribbean Cruises Ltd."],
  ["CSX", "CSX Corporation"],
  ["EOG", "EOG Resources, Inc."],
  ["AEP", "American Electric Power Company, Inc."],
  ["CL", "Colgate-Palmolive Company"],
  ["CI", "The Cigna Group"],
  ["MDLZ", "Mondelez International, Inc."],
  ["DASH", "DoorDash, Inc."],
  ["PSX", "Phillips 66"],
  ["RSG", "Republic Services, Inc."],
  ["VLO", "Valero Energy Corporation"],
  ["AON", "Aon plc"],
  ["TDG", "TransDigm Group Incorporated"],
  ["COR", "Cencora, Inc."],
  ["WBD", "Warner Bros. Discovery, Inc."],
  ["ROST", "Ross Stores, Inc."],
  ["LHX", "L3Harris Technologies, Inc."],
  ["SLB", "SLB N.V."],
  ["HLT", "Hilton Worldwide Holdings Inc."],
  ["CRH", "CRH plc"],
  ["MPC", "Marathon Petroleum Corporation"],
  ["HOOD", "Robinhood Markets, Inc."],
  ["GM", "General Motors Company"],
  ["TRV", "The Travelers Companies, Inc."],
  ["NSC", "Norfolk Southern Corporation"],
  ["ELV", "Elevance Health, Inc."],
  ["APD", "Air Products and Chemicals, Inc."],
  ["SRE", "Sempra"],
  ["FTNT", "Fortinet, Inc."],
  ["DLR", "Digital Realty Trust, Inc."],
  ["SPG", "Simon Property Group, Inc."],
  ["PCAR", "PACCAR Inc"],
  ["APO", "Apollo Global Management, Inc."],
  ["O", "Realty Income Corporation"],
  ["AZO", "AutoZone, Inc."],
  ["TEL", "TE Connectivity plc"],
  ["OXY", "Occidental Petroleum Corporation"],
  ["AFL", "Aflac Incorporated"],
  ["D", "Dominion Energy, Inc."],
  ["TFC", "Truist Financial Corporation"],
  ["OKE", "ONEOK, Inc."],
  ["ALL", "The Allstate Corporation"],
  ["BKR", "Baker Hughes Company"],
  ["VST", "Vistra Corp."],
  ["AJG", "Arthur J. Gallagher & Co."],
  ["CTVA", "Corteva, Inc."],
  ["TGT", "Target Corporation"],
  ["ADSK", "Autodesk, Inc."],
  ["PSA", "Public Storage"],
  ["FAST", "Fastenal Company"],
  ["MPWR", "Monolithic Power Systems, Inc."],
  ["COIN", "Coinbase Global, Inc."],
  ["TRGP", "Targa Resources Corp."],
  ["FANG", "Diamondback Energy, Inc."],
  ["XEL", "Xcel Energy Inc."],
  ["CAH", "Cardinal Health, Inc."],
  ["EXC", "Exelon Corporation"],
  ["GWW", "W.W. Grainger, Inc."],
  ["EA", "Electronic Arts Inc."],
  ["AME", "AMETEK, Inc."],
  ["ZTS", "Zoetis Inc."],
  ["NDAQ", "Nasdaq, Inc."],
  ["NXPI", "NXP Semiconductors N.V."],
  ["FIX", "Comfort Systems USA, Inc."],
  ["KEYS", "Keysight Technologies, Inc."],
  ["ETR", "Entergy Corporation"],
  ["CIEN", "Ciena Corporation"],
  ["EW", "Edwards Lifesciences Corporation"],
  ["CARR", "Carrier Global Corporation"],
  ["F", "Ford Motor Company"],
  ["URI", "United Rentals, Inc."],
  ["KR", "The Kroger Co."],
  ["IDXX", "IDEXX Laboratories, Inc."],
  ["BDX", "Becton, Dickinson and Company"],
  ["GRMN", "Garmin Ltd."],
  ["TER", "Teradyne, Inc."],
  ["YUM", "Yum! Brands, Inc."],
  ["MET", "MetLife, Inc."],
  ["HSY", "The Hershey Company"],
  ["DDOG", "Datadog, Inc."],
  ["CVNA", "Carvana Co."],
  ["CMG", "Chipotle Mexican Grill, Inc."],
  ["PEG", "Public Service Enterprise Group Incorporated"],
  ["ED", "Consolidated Edison, Inc."],
  ["PYPL", "PayPal Holdings, Inc."],
  ["AIG", "American International Group, Inc."],
  ["VTR", "Ventas, Inc."],
  ["SYY", "Sysco Corporation"],
  ["EBAY", "eBay Inc."],
  ["DHI", "D.R. Horton, Inc."],
  ["ROK", "Rockwell Automation, Inc."],
  ["WAB", "Westinghouse Air Brake Technologies Corporation"],
  ["AMP", "Ameriprise Financial, Inc."],
  ["MSCI", "MSCI Inc."],
  ["EQT", "EQT Corporation"],
  ["CBRE", "CBRE Group, Inc."],
  ["AXON", "Axon Enterprise, Inc."],
  ["FITB", "Fifth Third Bancorp"],
  ["TTWO", "Take-Two Interactive Software, Inc."],
  ["DAL", "Delta Air Lines, Inc."],
  ["WEC", "WEC Energy Group, Inc."],
  ["CCI", "Crown Castle Inc."],
  ["ODFL", "Old Dominion Freight Line, Inc."],
  ["NUE", "Nucor Corporation"],
  ["KDP", "Keurig Dr Pepper Inc."],
  ["HIG", "The Hartford Insurance Group, Inc."],
  ["TPL", "Texas Pacific Land Corporation"],
  ["LYV", "Live Nation Entertainment, Inc."],
  ["ROP", "Roper Technologies, Inc."],
  ["LVS", "Las Vegas Sands Corp."],
  ["XYZ", "Block, Inc."],
  ["MLM", "Martin Marietta Materials, Inc."],
  ["VMC", "Vulcan Materials Company"],
  ["ADM", "Archer-Daniels-Midland Company"],
  ["WDAY", "Workday, Inc."],
  ["STT", "State Street Corporation"],
  ["RMD", "ResMed Inc."],
  ["KVUE", "Kenvue Inc."],
  ["MCHP", "Microchip Technology Incorporated"],
  ["ACGL", "Arch Capital Group Ltd."],
  ["PAYX", "Paychex, Inc."],
  ["CPRT", "Copart, Inc."],
  ["KMB", "Kimberly-Clark Corporation"],
  ["OTIS", "Otis Worldwide Corporation"],
  ["GEHC", "GE HealthCare Technologies Inc."],
  ["IR", "Ingersoll Rand Inc."],
  ["PRU", "Prudential Financial, Inc."],
  ["EL", "The Estee Lauder Companies Inc."],
  ["EME", "EMCOR Group, Inc."],
  ["IRM", "Iron Mountain Incorporated"],
  ["A", "Agilent Technologies, Inc."],
  ["ATO", "Atmos Energy Corporation"],
  ["DTE", "DTE Energy Company"],
  ["AEE", "Ameren Corporation"],
  ["HBAN", "Huntington Bancshares Incorporated"],
  ["VICI", "VICI Properties Inc."],
  ["FISV", "Fiserv, Inc."],
  ["CBOE", "Cboe Global Markets, Inc."],
  ["EXR", "Extra Space Storage Inc."],
  ["CCL", "Carnival Corporation & plc"],
  ["TDY", "Teledyne Technologies Incorporated"],
  ["FE", "FirstEnergy Corp."],
  ["IBKR", "Interactive Brokers Group, Inc."],
  ["MTB", "M&T Bank Corporation"],
  ["XYL", "Xylem Inc."],
  ["DG", "Dollar General Corporation"],
  ["PPL", "PPL Corporation"],
  ["CTSH", "Cognizant Technology Solutions Corporation"],
  ["TPR", "Tapestry, Inc."],
  ["RJF", "Raymond James Financial, Inc."],
  ["CNP", "CenterPoint Energy, Inc."],
  ["DVN", "Devon Energy Corporation"],
  ["HPE", "Hewlett Packard Enterprise Company"],
  ["HAL", "Halliburton Company"],
  ["WAT", "Waters Corporation"],
  ["UAL", "United Airlines Holdings, Inc."],
  ["EXPE", "Expedia Group, Inc."],
  ["IQV", "IQVIA Holdings Inc."],
  ["VRSK", "Verisk Analytics, Inc."],
  ["CHTR", "Charter Communications, Inc."],
  ["EIX", "Edison International"],
  ["DOV", "Dover Corporation"],
  ["ES", "Eversource Energy"],
  ["WTW", "Willis Towers Watson Public Limited Company"],
  ["AWK", "American Water Works Company, Inc."],
  ["FICO", "Fair Isaac Corporation"],
  ["KHC", "The Kraft Heinz Company"],
  ["BIIB", "Biogen Inc."],
  ["ROL", "Rollins, Inc."],
  ["JBL", "Jabil Inc."],
  ["DOW", "Dow Inc."],
  ["STZ", "Constellation Brands, Inc."],
  ["WRB", "W. R. Berkley Corporation"],
  ["EXE", "Expand Energy Corporation"],
  ["FIS", "Fidelity National Information Services, Inc."],
  ["CINF", "Cincinnati Financial Corporation"],
  ["NTRS", "Northern Trust Corporation"],
  ["TSCO", "Tractor Supply Company"],
  ["HUBB", "Hubbell Incorporated"],
  ["DXCM", "DexCom, Inc."],
  ["STLD", "Steel Dynamics, Inc."],
  ["FOXA", "Fox Corporation (Class A)"],
  ["CTRA", "Coterra Energy Inc."],
  ["OMC", "Omnicom Group Inc."],
  ["BG", "Bunge Global SA"],
  ["MTD", "Mettler-Toledo International Inc."],
  ["CMS", "CMS Energy Corporation"],
  ["ULTA", "Ulta Beauty, Inc."],
  ["AVB", "AvalonBay Communities, Inc."],
  ["CFG", "Citizens Financial Group, Inc."],
  ["LEN", "Lennar Corporation"],
  ["DRI", "Darden Restaurants, Inc."],
  ["LYB", "LyondellBasell Industries N.V."],
  ["BRO", "Brown & Brown, Inc."],
  ["CHD", "Church & Dwight Co., Inc."],
  ["ON", "ON Semiconductor Corporation"],
  ["PHM", "PulteGroup, Inc."],
  ["Q", "Qnity Electronics, Inc."],
  ["ARES", "Ares Management Corporation"],
  ["PPG", "PPG Industries, Inc."],
  ["NI", "NiSource Inc."],
  ["EQR", "Equity Residential"],
  ["VLTO", "Veralto Corporation"],
  ["L", "Loews Corporation"],
  ["SYF", "Synchrony Financial"],
  ["EFX", "Equifax Inc."],
  ["FOX", "Fox Corporation (Class B)"],
  ["LDOS", "Leidos Holdings, Inc."],
  ["DGX", "Quest Diagnostics Incorporated"],
  ["VRSN", "VeriSign, Inc."],
  ["LH", "Labcorp Holdings Inc."],
  ["CPAY", "Corpay, Inc."],
  ["RF", "Regions Financial Corporation"],
  ["WSM", "Williams-Sonoma, Inc."],
  ["DLTR", "Dollar Tree, Inc."],
  ["TSN", "Tyson Foods, Inc."],
  ["STE", "STERIS plc"],
  ["FSLR", "First Solar, Inc."],
  ["GIS", "General Mills, Inc."],
  ["SW", "Smurfit Westrock Plc"],
  ["BR", "Broadridge Financial Solutions, Inc."],
  ["MRNA", "Moderna, Inc."],
  ["KEY", "KeyCorp"],
  ["CHRW", "C.H. Robinson Worldwide, Inc."],
  ["RL", "Ralph Lauren Corporation"],
  ["HUM", "Humana Inc."],
  ["CF", "CF Industries Holdings, Inc."],
  ["SBAC", "SBA Communications Corporation"],
  ["IP", "International Paper Company"],
  ["NTAP", "NetApp, Inc."],
  ["TROW", "T. Rowe Price Group, Inc."],
  ["GPN", "Global Payments Inc."],
  ["PKG", "Packaging Corporation of America"],
  ["SNA", "Snap-on Incorporated"],
  ["LUV", "Southwest Airlines Co."],
  ["EXPD", "Expeditors International of Washington, Inc."],
  ["EVRG", "Evergy, Inc."],
  ["JBHT", "J.B. Hunt Transport Services, Inc."],
  ["AMCR", "Amcor plc"],
  ["LNT", "Alliant Energy Corporation"],
  ["ALB", "Albemarle Corporation"],
  ["PFG", "Principal Financial Group, Inc."],
  ["PTC", "PTC Inc."],
  ["ZBH", "Zimmer Biomet Holdings, Inc."],
  ["SMCI", "Super Micro Computer, Inc."],
  ["INCY", "Incyte Corporation"],
  ["DD", "DuPont de Nemours, Inc."],
  ["CSGP", "CoStar Group, Inc."],
  ["NVR", "NVR, Inc."],
  ["IFF", "International Flavors & Fragrances Inc."],
  ["LULU", "lululemon athletica inc."],
  ["HPQ", "HP Inc."],
  ["WST", "West Pharmaceutical Services, Inc."],
  ["CNC", "Centene Corporation"],
  ["WY", "Weyerhaeuser Company"],
  ["HOLX", "Hologic, Inc."],
  ["LII", "Lennox International Inc."],
  ["FTV", "Fortive Corporation"],
  ["BALL", "Ball Corporation"],
  ["FFIV", "F5, Inc."],
  ["HII", "Huntington Ingalls Industries, Inc."],
  ["ESS", "Essex Property Trust, Inc."],
  ["TXT", "Textron Inc."],
  ["MKC", "McCormick & Company, Incorporated"],
  ["AKAM", "Akamai Technologies, Inc."],
  ["VTRS", "Viatris Inc."],
  ["TRMB", "Trimble Inc."],
  ["PODD", "Insulet Corporation"],
  ["KIM", "Kimco Realty Corporation"],
  ["INVH", "Invitation Homes Inc."],
  ["TKO", "TKO Group Holdings, Inc."],
  ["J", "Jacobs Solutions Inc."],
  ["TYL", "Tyler Technologies, Inc."],
  ["APTV", "Aptiv PLC"],
  ["CDW", "CDW Corporation"],
  ["NDSN", "Nordson Corporation"],
  ["MAA", "Mid-America Apartment Communities, Inc."],
  ["GPC", "Genuine Parts Company"],
  ["PNR", "Pentair plc"],
  ["DECK", "Deckers Outdoor Corporation"],
  ["REG", "Regency Centers Corporation"],
  ["IEX", "IDEX Corporation"],
  ["COO", "The Cooper Companies, Inc."],
  ["DPZ", "Domino's Pizza, Inc."],
  ["CLX", "The Clorox Company"],
  ["HAS", "Hasbro, Inc."],
  ["AVY", "Avery Dennison Corporation"],
  ["BBY", "Best Buy Co., Inc."],
  ["NWSA", "News Corporation (Class A)"],
  ["TTD", "The Trade Desk, Inc."],
  ["EG", "Everest Group, Ltd."],
  ["ERIE", "Erie Indemnity Company"],
  ["HST", "Host Hotels & Resorts, Inc."],
  ["BEN", "Franklin Resources, Inc."],
  ["MAS", "Masco Corporation"],
  ["GEN", "Gen Digital Inc."],
  ["ALLE", "Allegion plc"],
  ["HRL", "Hormel Foods Corporation"],
  ["PNW", "Pinnacle West Capital Corporation"],
  ["JKHY", "Jack Henry & Associates, Inc."],
  ["APA", "APA Corporation"],
  ["DOC", "Healthpeak Properties, Inc."],
  ["GNRC", "Generac Holdings Inc."],
  ["UHS", "Universal Health Services, Inc."],
  ["IT", "Gartner, Inc."],
  ["ALGN", "Align Technology, Inc."],
  ["UDR", "UDR, Inc."],
  ["SOLV", "Solventum Corporation"],
  ["SJM", "The J. M. Smucker Company"],
  ["PSKY", "Paramount Skydance Corporation"],
  ["GDDY", "GoDaddy Inc."],
  ["GL", "Globe Life Inc."],
  ["SWK", "Stanley Black & Decker, Inc."],
  ["AIZ", "Assurant, Inc."],
  ["BF.B", "Brown-Forman Corporation"],
  ["WYNN", "Wynn Resorts, Limited"],
  ["CPT", "Camden Property Trust"],
  ["IVZ", "Invesco Ltd."],
  ["AES", "The AES Corporation"],
  ["DVA", "DaVita Inc."],
  ["ZBRA", "Zebra Technologies Corporation"],
  ["BLDR", "Builders FirstSource, Inc."],
  ["RVTY", "Revvity, Inc."],
  ["MGM", "MGM Resorts International"],
  ["MOS", "The Mosaic Company"],
  ["AOS", "A. O. Smith Corporation"],
  ["FRT", "Federal Realty Investment Trust"],
  ["BAX", "Baxter International Inc."],
  ["HSIC", "Henry Schein, Inc."],
  ["NCLH", "Norwegian Cruise Line Holdings Ltd."],
  ["ARE", "Alexandria Real Estate Equities, Inc."],
  ["BXP", "BXP, Inc."],
  ["SWKS", "Skyworks Solutions, Inc."],
  ["TECH", "Bio-Techne Corporation"],
  ["CAG", "Conagra Brands, Inc."],
  ["TAP", "Molson Coors Beverage Company"],
  ["MOH", "Molina Healthcare, Inc."],
  ["CRL", "Charles River Laboratories International, Inc."],
  ["FDS", "FactSet Research Systems Inc."],
  ["POOL", "Pool Corporation"],
  ["EPAM", "EPAM Systems, Inc."],
  ["MTCH", "Match Group, Inc."],
  ["PAYC", "Paycom Software, Inc."],
  ["CPB", "The Campbell's Company"],
  ["LW", "Lamb Weston Holdings, Inc."],
  ["PCG", "PG&E Corporation"],
  ["NWS", "News Corporation (Class B)"],
];
